{{ if .Values.aws_csi_driver.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
  labels:
    kn: "knite-1"
  annotations:
    argocd.argoproj.io/sync-wave: "1"    
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.dest_server }}
  project: default
  source:
    path: eks-aws-ebs-csi
    repoURL: https://github.com/mamonteiro-devops/confluent-kafka-eks.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false 
{{ end }}