{{ if .Values.external_dns.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  labels:
    kn: "knite-1"
  annotations:
    argocd.argoproj.io/sync-wave: "3"    
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: externaldns
    server: {{ .Values.dest_server }}
  project: default
  source:
    path: eks-externaldns
    repoURL: https://github.com/mamonteiro-devops/confluent-kafka-eks.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
{{ end }}      