#{{ if .Values.kube_prometheus_stack.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  labels:
    kn: "knite-1"
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: {{ .Values.dest_server }}
  project: default
  source:
    path: kafka-management
    repoURL: https://github.com/mamonteiro-devops/confluent-kafka-eks.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
#{{ end }}