apiVersion: v2
name: external-dns
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0"
dependencies:
  - name: external-dns
    repository: https://charts.bitnami.com/bitnami
    version: 6.17.0
