server:
  service:
    type: NodePort

configs:
  secret:
    argocdServerAdminPassword: $2a$10$CAF82t.Bs.C030HGplOLZebyppdkBGliti03ZAKqmJJTh3Mf95cBq

  cm:
    exec.enabled: false
    resource.customizations: |
      platform.confluent.io/ControlCenter:
        health.lua: |
          hs = {}
          hs.status = "Healthy"
          hs.message = ""
          return hs
